
name: Sample Task
description: Sample description about this task

sources:
  - name: somename1
    type: inventoryS3
    params:
      language: en
      pos: br
  - name: somename2
    type: mysql
    params:
      host: localhost
      port: 3360
      user: user
      pass: pass

hooks:
  - name: hook1
    type: inventoryS3
    params:
      language: en
      pos: br
  - name: hook2
    type: foo
    params:
      bar: baz
      baz: true

outputs:
  - name: output1
    type: foo
    params:
      bar: baz
      baz: true
  - name: output2
    type: foo
    params:
      bar: baz
      baz: true
